### ISSUE TITLE
Possible matplotlib backend issue on OS X (default to TkAgg?)

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/AmesPAHdbPythonSuite#1]
Ran into this while working on the dev branch, while using `Matplotlib 3.0.2`, `Python 3.7.2`, `Numpy 1.16.2` on `Mac OS X 10.14.3`, environment was set up with `Conda`. Error:

> 2019-03-12 10:48:23.388 python[39527:1103627] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb21d27d0e0
2019-03-12 10:48:23.391 python[39527:1103627] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb21d27d0e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3780cded __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff638d4720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3788a195 -[NSObject(NSObject) __retain_OA] + 0
         ....
	126 python                              0x0000000105ec3bbd main + 125
	127 libdyld.dylib                       0x00007fff649a2ed9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

(Clipped the middle bits out for brevity.)

Apparently this has cropped up before when using Matplotlib on OS X, e,g., 
https://github.com/MTG/sms-tools/issues/36
https://github.com/vlajnaya-mol/message-analyser/issues/1

As suggested in the links above, this fixed the issue:
`$ mkdir -p ~/.matplotlib`
`$ echo "backend: TkAgg" > ~/.matplotlib/matplotlibrc`

Might need to incorporate a default TkAgg backend in some scenarios. Not sure what the underlying cause is though.

**Comment by jennyfolkesson** [comment]
I have the exact same issue using the same versions of numpy and python, with Matplotlib 3.0.3 and OSX 10.13.4.

**Comment by PAHdb** [comment]
This is a Matplotlib issue and will need to be fixed on their end---we can not be expected to have work arounds for all possible issues in other libraries; although, we do have one in place for a Multiprocessing issue under MacOS ...
